version: "3.8"

services:
  bot:
    build: .
    container_name: telegram-432hz-bot-single
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NODE_ENV=production
      - TEMP_DIR=/app/temp
      - FFMPEG_PATH=/usr/bin/ffmpeg
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
